services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  turismo-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
    container_name: turismo-api
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  mongo-data:
